unit Languages;

interface
  type
   LanguageID=(lIDEngish,lIDPersian);
  procedure SwitchProgramLanguage(Language:LanguageID);

implementation
  uses
    MainUnit,Classes, SysUtils, Forms;

procedure ChangeMainFormLanguage(Language:LanguageID);

procedure ChangeMenusLanguage(Language:LanguageID);
begin
  with MainForm do
  case Language of
  lIDEngish:
  begin
    //*********Main Menu***************
    File1.Caption:='File';
      NewWorkProject1.Caption:='New Work Project';
      OpenWorkProject1.Caption:='Open Work Project...';
      SaveWorkProject1.Caption:='Save Work Project';
      SaveWorkAs.Caption:='Save Work Project As...';
      LoadDataSheet1.Caption:='Load Data Sheet From File...';
      LoadDataSheetXLS.Caption:='Load Data Sheet From MS Excel File...';
      AppendDataSheet1.Caption:='Append Data Sheet...';
      SaveDataSheetAs1.Caption:='Save Data Sheet As';
        MicrosoftExcell1.Caption:='Microsoft Excel Spread Sheet...';
        MicrosoftExcel2.Caption:='Microsoft Excel Named Spread Sheet...';
        WordDocument1.Caption:='Word Document...';
        HTMLFile1.Caption:='HTML File...';
        TextFile1.Caption:='Text File...';
      Print2.Caption:='Print';
        PrintDataSheet.Caption:='Data Sheet...';
        PrintChart.Caption:='Chart...';
      PrinterSetup1.Caption:='Printer Setup...';
      Exit1.Caption:='Exit';
    Edit1.Caption:='Edit';
      MCut.Caption:='Cut';
      MCopy.Caption:='Copy';
      MPaste.Caption:='Paste';
    View1.Caption:='View';
      MemberPane2.Caption:='Member Pane';
      DettachAttachPane.Caption:='Dettach Member Pane';
      MemberPane1.Caption:='View Member Pane As';
        ListView1.Caption:='List View';
        IconView1.Caption:='Icon View';
        ToolBarView1.Caption:='Tool Bar View';
        MenuView1.Caption:='Menu View';
      ToolBars.Caption:='Toolbars';
        GlobalToolbar1.Caption:='Global Toolbar';
        ChartToolbar1.Caption:='Chart Toolbar';
        FastCalc1.Caption:='Fast Calc Toolbar';
      StatusBar1.Caption:='Status Bar';
      HideWhenMinimized1.Caption:='Hide When minimized';
    DataSheetMainMenu.Caption:='Data Sheet';
      MSort.Caption:='Sort Values';
      MResize.Caption:='R&esize To';
        MGretestColumn.Caption:='Greatest Column Width';
        MSmallestColumn.Caption:='Smallest Column Width';
        MDefault.Caption:='Default';
      MFind.Caption:='Find On Sheet...';
      MReplace.Caption:='Find And Replace...';
      MPrint.Caption:='Print...';
      MGStyle.Caption:='Style';
        MStyleDefault.Caption:='Default';
        MStyleClassic.Caption:='Classic';
        MStyleFlat.Caption:='Flat';
      MFont.Caption:='Font...';
{      MShowBackImage.Caption:='Show Background Picture';
      MGBackPicture.Caption:='Background Picture';
        MImageDefault.Caption:='Default';
        MChoosePicture.Caption:='Choose Picture...';
        MNoBackground.Caption:='No Background';}
    Chart3.Caption:='Chart';
      c1.Caption:='View Separated Chart';
      PrintChart1.Caption:='Print Chart...';
      c3.Caption:='Copy To Clipboard As Picture';
      c4.Caption:='Copy To Clipboard As Metafile';
      c5.Caption:='Save To File As Picture...';
      c6.Caption:='Save To File As Metafile...';
    Tools1.Caption:='Tools';
      FormulaEditor1.Caption:='Formula Editor...';
      RandomNumberProducer1.Caption:='Random Number Producer...';
    Help1.Caption:='Help';
      StatManHelp1.Caption:='StatMan English Help';
      StatManHelp2.Caption:='StatMan Persian Help';
      DefaultHelpLanguage1.Caption:='Default Help Language';
        EnglishHelp.Caption:='English';
        PersianHelp.Caption:='Persian';
      HelpStyle1.Caption:='Help Style';
        PromptForLan.Caption:='Prompt To Choose Help Language';
        ShowDefaultLan.Caption:='Show Help For Default Help Language';
      About1.Caption:='&About...';
      Notes1.Caption:='Notes';
      TipOfTheDay.Caption:='Tip of the Day';
  end;
  lIDPersian:
  begin
    File1.Caption:='›«Ì·';
      NewWorkProject1.Caption:='Å—ÊéÂ ò«—Ì ÃœÌœ';
      OpenWorkProject1.Caption:='...»«“ ò—œ‰ Å—ÊéÂ ò«—Ì';
      SaveWorkProject1.Caption:='–ŒÌ—Â Å—ÊéÂ ò«—Ì';
      SaveWorkAs.Caption:='...–ŒÌ—Â Å—ÊéÂ ò«—Ì »« ⁄‰Ê«‰ œÌê—';
      LoadDataSheet1.Caption:='...»«—ò—œ‰ »—êÂ œ«œÂ Â« «“ ›«Ì·';
      LoadDataSheetXLS.Caption:='...»«—ò—œ‰ »—êÂ œ«œÂ Â« «“ Ìò ›«Ì· «ò”·';
      AppendDataSheet1.Caption:='...«·Õ«ﬁ ò—œ‰ »Â »—êÂ œ«œÂ Â«';
      SaveDataSheetAs1.Caption:='–ŒÌ—Â »—êÂ œ«œÂ Â« »Â ’Ê— ';
        MicrosoftExcell1.Caption:='...»—êÂ ’›ÕÂ ê” —œÂ «ò”·';
        MicrosoftExcel2.Caption:='...»—êÂ ’›ÕÂ ê” —œÂ œ«—«Ì ‰«„ «ò”·';
        WordDocument1.Caption:='...Word ”‰œ „ ‰Ì »—‰«„Â ';
        HTMLFile1.Caption:='...HTML ›«Ì· ';
        TextFile1.Caption:='...›«Ì· „ ‰Ì';
      Print2.Caption:='ç«Å';
        PrintDataSheet.Caption:='...»—êÂ œ«œÂ Â«';
        PrintChart.Caption:='...‰„Êœ«—';
      PrinterSetup1.Caption:='... ‰ŸÌ„«  ç«Åê—';
      Exit1.Caption:='Œ—ÊÃ';
    Edit1.Caption:='ÊÌ—«Ì‘';
      MCut.Caption:='Cut';
      MCopy.Caption:='òÅÌ';
      MPaste.Caption:='Paste';
    View1.Caption:='Ÿ«Â—';
      MemberPane2.Caption:='Member Pane';
//      MemberPane1.Caption:='»’Ê—  Member Pane Ÿ«Â—';
        ListView1.Caption:='»‘ò· ·Ì” ';
        IconView1.Caption:='»‘ò· ¬ÌòÊ‰';
        ToolBarView1.Caption:='»‘ò· ‰Ê«— «»“«—';
        MenuView1.Caption:='»‘ò· „‰Ê';
      ToolBars.Caption:='‰Ê«—Â«Ì «»“«—';
        GlobalToolbar1.Caption:='‰Ê«— «»“«— ⁄„Ê„Ì';
        ChartToolbar1.Caption:='‰Ê«— «»“«— ‰„Êœ«—';
        FastCalc1.Caption:='Fast Calc ‰Ê«— «»“«— ';
      StatusBar1.Caption:='‰Ê«— Ê÷⁄Ì ';
      HideWhenMinimized1.Caption:='Â‰ê«„ òÊçò ò—œ‰ „Œ›Ì ‘Êœ';
    DataSheetMainMenu.Caption:='»—êÂ œ«œÂ Â«';
      MSort.Caption:='„— » ò—œ‰ „ﬁ«œÌ—';
      MResize.Caption:=' €ÌÌ— «‰œ«“Â »Â';
        MGretestColumn.Caption:='»“—ê —Ì‰ ⁄—÷ ” Ê‰Â«';
        MSmallestColumn.Caption:='òÊçò —Ì‰ ⁄—÷ ” Ê‰Â«';
        MDefault.Caption:='⁄—÷ ÅÌ‘ ›—÷';
      MFind.Caption:='...Ã” ÃÊ œ— »—êÂ œ«œÂ Â«';
      MReplace.Caption:='...Ã” ÃÊ Ê Ã«Ìê–«—Ì';
      MPrint.Caption:='...ç«Å';
      MGStyle.Caption:=' ‰Ê⁄ »—êÂ œ«œÂ Â«';
        MStyleDefault.Caption:='ÅÌ‘ ›—÷';
        MStyleClassic.Caption:='⁄«œÌ';
        MStyleFlat.Caption:='„”ÿÕ';
      MFont.Caption:='...›Ê‰  ';
{      MShowBackImage.Caption:='‰„«Ì‘ Å‘  “„Ì‰Â';
      MGBackPicture.Caption:=' ’ÊÌ— Å‘  “„Ì‰Â';
        MImageDefault.Caption:='ÅÌ‘ ›—÷';
        MChoosePicture.Caption:='...«‰ Œ«»  ’ÊÌ—';
        MNoBackground.Caption:='»œÊ‰  ’ÊÌ— Å‘  “„”‰Â';}
    Chart3.Caption:='‰„Êœ«—';
      c1.Caption:='‰„«Ì‘ ‰„Êœ«— œ— Å‰Ã—Â œÌê—';
      PrintChart1.Caption:='...ç«Å ‰„Êœ«—';
      c3.Caption:='òÅÌ ‰„Êœ«— »’Ê—   ’ÊÌ—';
      c4.Caption:='òÅÌ ‰„Êœ«— »’Ê—  ﬁ«·»  —”Ì„Ì';
      c5.Caption:='...–ŒÌ—Â ‰„Êœ«— »’Ê—   ’ÊÌ—';
      c6.Caption:='...–ŒÌ—Â ‰„Êœ«— »’Ê—  ›«Ì·  —”Ì„';
    Tools1.Caption:='«»“«—Â«';
      FormulaEditor1.Caption:='...ÊÌ—«Ì‘ê— ›—„Ê·';
      RandomNumberProducer1.Caption:='... Ê·Ìœ ò‰‰œÂ «⁄œ«œ  ’«œ›Ì';
    Help1.Caption:='—«Â‰„«';
      StatManHelp1.Caption:='—«Â‰„«Ì «‰ê·Ì”Ì';
      StatManHelp2.Caption:='—«Â‰„«Ì ›«—”Ì';
      DefaultHelpLanguage1.Caption:='“»«‰ ÅÌ‘ ›—÷ —«Â‰„«';
        EnglishHelp.Caption:='«‰ê·Ì”Ì';
        PersianHelp.Caption:='›«—”Ì';
      HelpStyle1.Caption:='‰ÕÊÂ ‰„«Ì‘ —«Â‰„«';
        PromptForLan.Caption:='«‰ Œ«» “»«‰ „Ê—œ‰Ÿ— ﬁ»· «“ ‰„«Ì‘ —«Â‰„«';
        ShowDefaultLan.Caption:='‰„«Ì‘ —«Â‰„« »« “»«‰ ÅÌ‘ ›—÷';
      About1.Caption:='...œ—»«—Â ‰—„ «›“«—';
      Notes1.Caption:='Ì«œœ«‘ ';
      TipOfTheDay.Caption:='‰ò«  „›Ìœ œ—»«—Â ‰ÕÊÂ «” ›«œÂ';
  end;
  end; {Case}
end;


begin
  ChangeMenusLanguage(Language);
{  if Language=lIDPersian then
    MainForm.MainMenu1.BiDiMode:=bdRightToLeft
  else
    MainForm.MainMenu1.BiDiMode:=bdLeftToRight;}
  with MainForm do
  case Language of
    lIDEngish: begin
                 SettingSection.Font.Name:='MS Sans Serif';
                 Sheet1Section.Font.Name:='MS Sans Serif';
                 Sheet2Section.Font.Name:='MS Sans Serif';
                 Sheet3Section.Font.Name:='MS Sans Serif';
                 Sheet4Section.Font.Name:='MS Sans Serif';
                 Sheet5Section.Font.Name:='MS Sans Serif';
                 TableSection.Font.Name:='MS Sans Serif';
                 ChartSection.Font.Name:='MS Sans Serif';
                 AnalyzeSection.Font.Name:='MS Sans Serif';
                 IconSettings.Font.Name:='MS Sans Serif';
                 IconSheet1.Font.Name:='MS Sans Serif';
                 IconSheet2.Font.Name:='MS Sans Serif';
                 IconSheet3.Font.Name:='MS Sans Serif';
                 IconSheet4.Font.Name:='MS Sans Serif';
                 IconSheet5.Font.Name:='MS Sans Serif';
                 IconTable.Font.Name:='MS Sans Serif';
                 IconChart.Font.Name:='MS Sans Serif';
                 IconAnalyze.Font.Name:='MS Sans Serif';
                 SettingTitle.Font.Name:='MS Sans Serif';
                 Sheet1Title.Font.Name:='MS Sans Serif';
                 Sheet2Title.Font.Name:='MS Sans Serif';
                 Sheet3Title.Font.Name:='MS Sans Serif';
                 Sheet4Title.Font.Name:='MS Sans Serif';
                 Sheet5Title.Font.Name:='MS Sans Serif';
                 FrequencyTableTitle.Font.Name:='MS Sans Serif';
                 ChartsTitle.Font.Name:='MS Sans Serif';
                 DataAnalyzingTitle.Font.Name:='MS Sans Serif';
                 SettingSection.Caption:='Data Settings';
                 Sheet1Section.Caption:='Data Sheet 1';
                 Sheet2Section.Caption:='Data Sheet 2';
                 Sheet3Section.Caption:='Data Sheet 3';
                 Sheet4Section.Caption:='Data Sheet 4';
                 Sheet5Section.Caption:='Data Sheet 5';
                 TableSection.Caption:='Frequency Table';
                 ChartSection.Caption:='Charts';
                 AnalyzeSection.Caption:='Data Analyzing';
                 IconSettings.Caption:='Data Settings';
                 IconSheet1.Caption:='Data Sheet 1';
                 IconSheet2.Caption:='Data Sheet 2';
                 IconSheet3.Caption:='Data Sheet 3';
                 IconSheet4.Caption:='Data Sheet 4';
                 IconSheet5.Caption:='Data Sheet 5';
                 IconTable.Caption:='Frequency Table';
                 IconChart.Caption:='Charts';
                 IconAnalyze.Caption:='Data Analyzing';
                 MSettingSection.Caption:='Data Settings';
                 MSheet1Section.Caption:='Data Sheet 1';
                 MSheet2Section.Caption:='Data Sheet 2';
                 MSheet3Section.Caption:='Data Sheet 3';
                 MSheet4Section.Caption:='Data Sheet 4';
                 MSheet5Section.Caption:='Data Sheet 5';
                 MTableSection.Caption:='Frequency Table';
                 MChartSection.Caption:='Charts';
                 MAnalyzeSection.Caption:='Data Analyzing';
                 ListView.Caption:='List View';
                 IconView.Caption:='Icon View';
                 ToolView.Caption:='Toolbar View';
                 MenuView.Caption:='Menu View';

                 SettingTitle.Alignment:=taRightJustify;
                 ChartsTitle.Alignment:=taRightJustify;
                 FrequencyTableTitle.Alignment:=taRightJustify;
                 DataAnalyzingTitle.Alignment:=taRightJustify;
                 Sheet1Title.Alignment:=taLeftJustify;
                 Sheet2Title.Alignment:=taLeftJustify;
                 Sheet3Title.Alignment:=taLeftJustify;
                 Sheet4Title.Alignment:=taLeftJustify;
                 Sheet5Title.Alignment:=taLeftJustify;
                 SettingTitle.Caption:='Data Settings';
                 ChartsTitle.Caption:='Data Chart';
                 FrequencyTableTitle.Caption:='Frequency Table';
                 DataAnalyzingTitle.Caption:='Analyze Data';
                 Sheet1Title.Caption:='Data Sheet 1';
                 Sheet2Title.Caption:='Data Sheet 2';
                 Sheet3Title.Caption:='Data Sheet 3';
                 Sheet4Title.Caption:='Data Sheet 4';
                 Sheet5Title.Caption:='Data Sheet 5';
                 CreateTable2.Caption:='Table Creator';
                 AnalyzeReportbtn.Caption:='Report';
                 Type1Title.Caption:='Type:';
                 Type2Title.Caption:='Type:';
                 Type3Title.Caption:='Type:';
                 Type4Title.Caption:='Type:';
                 Type5Title.Caption:='Type:';
                 Filter1Title.Caption:='Function Filter:';
                 Filter2Title.Caption:='Function Filter:';
                 Filter3Title.Caption:='Function Filter:';
                 Filter4Title.Caption:='Function Filter:';
                 Filter5Title.Caption:='Function Filter:';
                 Des1Title.Caption:='Description:';
                 Des2Title.Caption:='Description:';
                 Des3Title.Caption:='Description:';
                 Des4Title.Caption:='Description:';
                 Des5Title.Caption:='Description:';
                 Precision1Title.Caption:='Precision:';
                 Precision2Title.Caption:='Precision:';
                 Precision3Title.Caption:='Precision:';
                 Precision4Title.Caption:='Precision:';
                 Precision5Title.Caption:='Precision:';
                 AnalyzeReportbtn.Alignment:=taLeftJustify;
                 Type1Title.Alignment:=taLeftJustify;
                 Type2Title.Alignment:=taLeftJustify;
                 Type3Title.Alignment:=taLeftJustify;
                 Type4Title.Alignment:=taLeftJustify;
                 Type5Title.Alignment:=taLeftJustify;
                 Filter1Title.Alignment:=taLeftJustify;
                 Filter2Title.Alignment:=taLeftJustify;
                 Filter3Title.Alignment:=taLeftJustify;
                 Filter4Title.Alignment:=taLeftJustify;
                 Filter5Title.Alignment:=taLeftJustify;
                 Des1Title.Alignment:=taLeftJustify;
                 Des2Title.Alignment:=taLeftJustify;
                 Des3Title.Alignment:=taLeftJustify;
                 Des4Title.Alignment:=taLeftJustify;
                 Des5Title.Alignment:=taLeftJustify;
                 Precision1Title.Alignment:=taLeftJustify;
                 Precision2Title.Alignment:=taLeftJustify;
                 Precision3Title.Alignment:=taLeftJustify;
                 Precision4Title.Alignment:=taLeftJustify;
                 Precision5Title.Alignment:=taLeftJustify;
               end;
    lIDPersian: begin
                  SettingSection.Font.Name:='B Titr';
                  Sheet1Section.Font.Name:='B Titr';
                  Sheet2Section.Font.Name:='B Titr';
                  Sheet3Section.Font.Name:='B Titr';
                  Sheet4Section.Font.Name:='B Titr';
                  Sheet5Section.Font.Name:='B Titr';
                  TableSection.Font.Name:='B Titr';
                  ChartSection.Font.Name:='B Titr';
                  AnalyzeSection.Font.Name:='B Titr';
                  IconSettings.Font.Name:='B Titr';
                  IconSheet1.Font.Name:='B Titr';
                  IconSheet2.Font.Name:='B Titr';
                  IconSheet3.Font.Name:='B Titr';
                  IconSheet4.Font.Name:='B Titr';
                  IconSheet5.Font.Name:='B Titr';
                  IconTable.Font.Name:='B Titr';
                  IconChart.Font.Name:='B Titr';
                  IconAnalyze.Font.Name:='B Titr';
                  SettingTitle.Font.Name:='B Titr';
                  Sheet1Title.Font.Name:='B Titr';
                  Sheet2Title.Font.Name:='B Titr';
                  Sheet3Title.Font.Name:='B Titr';
                  Sheet4Title.Font.Name:='B Titr';
                  Sheet5Title.Font.Name:='B Titr';
                  FrequencyTableTitle.Font.Name:='B Titr';
                  ChartsTitle.Font.Name:='B Titr';
                  DataAnalyzingTitle.Font.Name:='B Titr';
                  SettingSection.Caption:=' ‰ŸÌ„«  œ«œÂ Â«';
                  Sheet1Section.Caption:='»—êÂ œ«œÂ Â« 1';
                  Sheet2Section.Caption:='»—êÂ œ«œÂ Â« 2';
                  Sheet3Section.Caption:='»—êÂ œ«œÂ Â« 3';
                  Sheet4Section.Caption:='»—êÂ œ«œÂ Â« 4';
                  Sheet5Section.Caption:='»—êÂ œ«œÂ Â« 5';
                  TableSection.Caption:='ÃœÊ· ›—«Ê«‰Ì';
                  ChartSection.Caption:='‰„Êœ«—Â«';
                  AnalyzeSection.Caption:=' Õ·Ì· œ«œÂ Â«';
                  IconSettings.Caption:=' ‰ŸÌ„«  œ«œÂ Â«';
                  IconSheet1.Caption:='»—êÂ œ«œÂ Â« 1';
                  IconSheet2.Caption:='»—êÂ œ«œÂ Â« 2';
                  IconSheet3.Caption:='»—êÂ œ«œÂ Â« 3';
                  IconSheet4.Caption:='»—êÂ œ«œÂ Â« 4';
                  IconSheet5.Caption:='»—êÂ œ«œÂ Â« 5';
                  IconTable.Caption:='ÃœÊ· ›—«Ê«‰Ì';
                  IconChart.Caption:='‰„Êœ«—Â«';
                  IconAnalyze.Caption:=' Õ·Ì· œ«œÂ Â«';
                  MSettingSection.Caption:=' ‰ŸÌ„«  œ«œÂ Â«';
                  MSheet1Section.Caption:='»—êÂ œ«œÂ Â« 1';
                  MSheet2Section.Caption:='»—êÂ œ«œÂ Â« 2';
                  MSheet3Section.Caption:='»—êÂ œ«œÂ Â« 3';
                  MSheet4Section.Caption:='»—êÂ œ«œÂ Â« 4';
                  MSheet5Section.Caption:='»—êÂ œ«œÂ Â« 5';
                  MTableSection.Caption:='ÃœÊ· ›—«Ê«‰Ì';
                  MChartSection.Caption:='‰„Êœ«—Â«';
                  MAnalyzeSection.Caption:=' Õ·Ì· œ«œÂ Â«';
                  ListView.Caption:='»‘ò· ·Ì” ';
                  IconView.Caption:='»‘ò· ¬ÌòÊ‰';
                  ToolView.Caption:='»‘ò· ‰Ê«— «»“«—';
                  MenuView.Caption:='»‘ò· „‰Ê';
                  SettingTitle.Alignment:=taRightJustify;
                  ChartsTitle.Alignment:=taRightJustify;
                  FrequencyTableTitle.Alignment:=taRightJustify;
                  DataAnalyzingTitle.Alignment:=taRightJustify;
                  Sheet1Title.Alignment:=taRightJustify;
                  Sheet2Title.Alignment:=taRightJustify;
                  Sheet3Title.Alignment:=taRightJustify;
                  Sheet4Title.Alignment:=taRightJustify;
                  Sheet5Title.Alignment:=taRightJustify;

                  SettingTitle.Caption:=' ‰ŸÌ„«  œ«œÂ Â«';
                  ChartsTitle.Caption:='‰„Êœ«— œ«œÂ Â«';
                  FrequencyTableTitle.Caption:='ÃœÊ· ›—«Ê«‰Ì';
                  DataAnalyzingTitle.Caption:=' Õ·Ì· œ«œÂ Â«';
                  Sheet1Title.Caption:='»—êÂ œ«œÂ Â« 1';
                  Sheet2Title.Caption:='»—êÂ œ«Â Â« 2';
                  Sheet3Title.Caption:='»—êÂ œ«œÂ Â« 3';
                  Sheet4Title.Caption:='»—êÂ œ«œÂ Â« 4';
                  Sheet5Title.Caption:='»—êÂ œ«œÂ Â« 5';
                  CreateTable2.Caption:='”«“‰œÂ ÃœÊ·';
                  AnalyzeReportbtn.Caption:='ê“«—‘';
                  Type1Title.Caption:='‰Ê⁄:';
                  Type2Title.Caption:='‰Ê⁄:';
                  Type3Title.Caption:='‰Ê⁄:';
                  Type4Title.Caption:='‰Ê⁄:';
                  Type5Title.Caption:='‰Ê⁄:';
                  Filter1Title.Caption:=' «»⁄ ›Ì· —:';
                  Filter2Title.Caption:=' «»⁄ ›Ì· —:';
                  Filter3Title.Caption:=' «»⁄ ›Ì· —:';
                  Filter4Title.Caption:=' «»⁄ ›Ì· —:';
                  Filter5Title.Caption:=' «»⁄ ›Ì· —:';
                  Des1Title.Caption:=' Ê÷ÌÕ« :';
                  Des2Title.Caption:=' Ê÷ÌÕ« :';
                  Des3Title.Caption:=' Ê÷ÌÕ« :';
                  Des4Title.Caption:=' Ê÷ÌÕ« :';
                  Des5Title.Caption:=' Ê÷ÌÕ« :';
                  Precision1Title.Caption:='œﬁ :';
                  Precision2Title.Caption:='œﬁ :';
                  Precision3Title.Caption:='œﬁ :';
                  Precision4Title.Caption:='œﬁ :';
                  Precision5Title.Caption:='œﬁ :';
                  AnalyzeReportbtn.Alignment:=taRightJustify;
                  Type1Title.Alignment:=taRightJustify;
                  Type2Title.Alignment:=taRightJustify;
                  Type3Title.Alignment:=taRightJustify;
                  Type4Title.Alignment:=taRightJustify;
                  Type5Title.Alignment:=taRightJustify;
                  Filter1Title.Alignment:=taRightJustify;
                  Filter2Title.Alignment:=taRightJustify;
                  Filter3Title.Alignment:=taRightJustify;
                  Filter4Title.Alignment:=taRightJustify;
                  Filter5Title.Alignment:=taRightJustify;
                  Des1Title.Alignment:=taRightJustify;
                  Des2Title.Alignment:=taRightJustify;
                  Des3Title.Alignment:=taRightJustify;
                  Des4Title.Alignment:=taRightJustify;
                  Des5Title.Alignment:=taRightJustify;
                  Precision1Title.Alignment:=taRightJustify;
                  Precision2Title.Alignment:=taRightJustify;
                  Precision3Title.Alignment:=taRightJustify;
                  Precision4Title.Alignment:=taRightJustify;
                  Precision5Title.Alignment:=taRightJustify;
                end;
  end;
end;

procedure SwitchProgramLanguage(Language:LanguageID);
begin
  ChangeMainFormLanguage(Language);
end;

end.
